/** Declaration file generated by dts-gen */

export const AnalyticsConsumer: {
    $$typeof: any;
    Consumer: any;
    Provider: {
        $$typeof: any;
    };
};

export const AnalyticsContext: {
    $$typeof: any;
    Consumer: {
        $$typeof: any;
        Consumer: any;
        Provider: {
            $$typeof: any;
        };
    };
    Provider: {
        $$typeof: any;
    };
    displayName: string;
};

export function AnalyticsProvider(_ref: any): any;

export function useAnalytics(): any;

export function useIdentify(): any;

export function usePage(): any;

export function useTrack(): any;

export function withAnalytics(Component: any): any;
